export type Venue = {
  id: string;
  name: string;
  short_code?: string | null;
  logo_url?: string | null;
  kickback_guest?: number | null;
  kickback_referrer?: number | null;
  payment_methods?: string[] | null;
  square_public?: boolean | null;
  billing_email?: string | null;
  billing_contact_first_name?: string | null;
  billing_contact_last_name?: string | null;
  billing_phone?: string | null;
  billing_company?: string | null;
  billing_country_code?: string | null;
  billing_state?: string | null;
  billing_postal_code?: string | null;
  billing_city?: string | null;
  billing_address?: string | null;
  billing_abn?: string | null;
  active?: boolean;
};
